#location of dataset for this file:https://drive.proton.me/urls/S2NHR5FHCM#CTkK2erKUVSK

---
date: '2022-10-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("tidyverse")
library("tidyverse")
```

```{r}
#Data Preperation

#add location of folder the dataset  is in here.

data <- read.csv("C:/Users/add location of folder here/PopTrendsBData3Aggs.csv")

#Here I am subtracting money won from money staked to figure out each persons net win/loss
data <- transform(data, winloss = StakeA - WinA)

#Creating dataset with just StakeA outliers
upperq <- quantile(data$StakeA)[4]
iqr <- IQR(data$StakeA)
StakeA_outliers <- data[which(data$StakeA > (upperq + iqr*3)),]

#Creating dataset with just winloss outliers
upperq <- quantile(data$winloss)[4]
lowerq <- quantile(data$winloss)[2]
iqr <- IQR(data$winloss)
winloss_outliers <- data[which(data$winloss < (lowerq - iqr*3) | data$winloss > (upperq + iqr*3)),]
```

```{r}
#Exploratory Data Analysis

summary(data$StakeA)
# Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
#   0.0     98.8    305.4   2770.7   1040.0 843123.6


#Here I am creating a box plot, and using quartile ranges to define outliers. The interquartile range is the difference between the 75% (upper) and 25% (lower) quartile. upper quartile + 3*interquartile range is the boundry for upper outliers, lower quartile - 3*interquartile range is the lower boundry for outliers.
boxplot(data$StakeA, ylim = c(0, 3000))
#Box plot is useless since there are 3391 outliers
#refer back to summary statistic
upperq <- quantile(data$StakeA)
lowerq <- quantile(data$StakeA)[2]
iqr <- IQR(data$StakeA)
iqr
num_outliers <- sum(data$StakeA > (upperq + 3*iqr))
num_outliers
#3391
nrow(data)
#46339

3391/46339
#0.0732, percentage of outliers, defined as 75% percentile +  3 * inter-quartile range.

d <- density(data$StakeA)
plot(d, xaxp=c(0, 15000, 10))
#Change the x-axis
```
```{r}

summary(data$winloss)

#    Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
#-38310.23     20.00     57.75    259.08    163.95  77293.73

#Doing the same analysis above but on the winloss metric I created.
upperqu <- quantile(data$winloss)[4]
lowerqu <- quantile(data$winloss)[2]
iqr <- IQR(data$winloss)
iqr
#143.9522
num_outliers1 <- sum(data$winloss < lowerqu - 3*iqr | data$winloss > upperqu + 3*iqr)
num_outliers1
#4840

#Here I turn the winloss metric into a probability distribution (sort of effective, sort of not) and creating a histogram to roughly understand the distribution. This part could use some better graphs. I suck at graphs
d_winloss <- density(data$winloss)
plot(d_winloss, xlim=c(-1000, 1000))
hist(data$winloss, breaks = 80)

```

```{r}

#Here I am creating a dataset of just upper outliers and exploring it. I need to do more exploratory analysis for this section
data
upperq <- quantile(data$StakeA)[4]
upperq
iqr <- IQR(data$StakeA)
StakeA_outliers <- data[which(data$StakeA > (upperq + iqr*3)),]
print(summary(StakeA_outliers))

print(summary(data))
```

```{r}
#Same analysis as above but with upper and lower outliers
data
upperq <- quantile(data$winloss)[4]
lowerq <- quantile(data$winloss)[2]
iqr <- IQR(data$winloss)
winloss_outliers <- data[which(data$winloss > (upperq + iqr*3) | data$winloss < (lowerq - iqr*3)),]
print(summary(winloss_outliers))

print(summary(data))
```

```{r}
#Looking at the differences in the money staked distribution between men and women.
test <- wilcox.test(StakeA ~ Gender, data = data)

newdata <- subset(data, Gender == 1)
newdata1 <- subset(data, Gender == 0)
summary(newdata$StakeA)
summary(newdata1$StakeA)

newdata3 <- subset(StakeA_outliers, Gender == 1)
newdata4 <- subset(StakeA_outliers, Gender == 0)
summary(newdata3$StakeA)
summary(newdata4$StakeA)
#Women generally spend less money on sport betting
#I'll add a statistical test to confirm this, and take note of test assumptions


#comparing money staked between men and women
summary(data$StakeA[data$Gender == 1])
summary(data$StakeA[data$Gender == 0])

#comparing money staked between men and women from outlier dataset (money staked)?
```

```{r}
data
```
